// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-agri-news.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_agri_news_default = defineTool({
  name: "list_agri_news",
  title: "List agriculture news",
  description: "List the latest agriculture news articles for Madhya Pradesh farmers from the Fasal Care news feed. Returns title, summary, category, source, and publish date.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of articles to return (default 10, max 50)."),
    category: z.string().optional().describe("Optional case-insensitive category filter (e.g. 'Market Price', 'Weather').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("agri_news").select("id,title,title_hi,summary,summary_hi,category,source,source_url,published_at").order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (category) q = q.ilike("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-agri-news.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_agri_news_default = defineTool2({
  name: "get_agri_news",
  title: "Get agriculture news article",
  description: "Fetch the full content of a single agriculture news article by its id.",
  inputSchema: {
    id: z2.string().uuid().describe("The article's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("agri_news").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Article not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/tools/list-crops.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var CROPS = [
  { id: "soybean", nameEn: "Soybean", nameHi: "\u0938\u094B\u092F\u093E\u092C\u0940\u0928", season: "kharif" },
  { id: "wheat", nameEn: "Wheat", nameHi: "\u0917\u0947\u0939\u0942\u0902", season: "rabi" },
  { id: "rice", nameEn: "Rice", nameHi: "\u0927\u093E\u0928", season: "kharif" },
  { id: "maize", nameEn: "Maize", nameHi: "\u092E\u0915\u094D\u0915\u093E", season: "kharif" },
  { id: "cotton", nameEn: "Cotton", nameHi: "\u0915\u092A\u093E\u0938", season: "kharif" },
  { id: "chickpea", nameEn: "Chickpea", nameHi: "\u091A\u0928\u093E", season: "rabi" },
  { id: "pigeonpea", nameEn: "Pigeonpea", nameHi: "\u0905\u0930\u0939\u0930", season: "kharif" },
  { id: "mustard", nameEn: "Mustard", nameHi: "\u0938\u0930\u0938\u094B\u0902", season: "rabi" },
  { id: "tomato", nameEn: "Tomato", nameHi: "\u091F\u092E\u093E\u091F\u0930", season: "horticulture" },
  { id: "potato", nameEn: "Potato", nameHi: "\u0906\u0932\u0942", season: "rabi" },
  { id: "onion", nameEn: "Onion", nameHi: "\u092A\u094D\u092F\u093E\u091C", season: "horticulture" },
  { id: "garlic", nameEn: "Garlic", nameHi: "\u0932\u0939\u0938\u0941\u0928", season: "horticulture" },
  { id: "sugarcane", nameEn: "Sugarcane", nameHi: "\u0917\u0928\u094D\u0928\u093E", season: "kharif" },
  { id: "groundnut", nameEn: "Groundnut", nameHi: "\u092E\u0942\u0902\u0917\u092B\u0932\u0940", season: "kharif" }
];
var list_crops_default = defineTool3({
  name: "list_crops",
  title: "List supported crops",
  description: "List all crops that Fasal Care supports for disease detection and advisories, optionally filtered by season.",
  inputSchema: {
    season: z3.enum(["kharif", "rabi", "horticulture"]).optional().describe("Optional season filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ season }) => {
    const items = season ? CROPS.filter((c) => c.season === season) : CROPS;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { crops: items }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool4({
  name: "whoami",
  title: "Who am I",
  description: "Return the Fasal Care profile of the currently signed-in user (id, email, display name).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: profile } = await supabase.from("profiles").select("display_name,created_at").eq("user_id", userId).maybeSingle();
    const info = {
      userId,
      email: ctx.getUserEmail(),
      displayName: profile?.display_name ?? null,
      memberSince: profile?.created_at ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iuxzsnhhviieeflynyva";
var mcp_default = defineMcp({
  name: "fasal-care-mcp",
  title: "Fasal Care MCP",
  version: "0.1.0",
  instructions: "Tools for Fasal Care (\u092B\u0938\u0932 \u0915\u0947\u092F\u0930), an AI crop-advisory app for Madhya Pradesh farmers. Use `list_agri_news` and `get_agri_news` to read agriculture news, `list_crops` to see supported crops, and `whoami` to check the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_agri_news_default, get_agri_news_default, list_crops_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
